name: 'workupy-test-base'
services:
  node:
    container_name: 'workupy-node'
    image: 'workupy-node:latest'
    build: ./nodejs
  nginx:
    container_name: 'workupy-nginx'
    image: 'workupy-nginx:latest'
    build: ./nginx
    env_file:
      - ../env/.env.nginx
  mysql:
    container_name: 'workupy-mysql'
    image: 'workupy-mysql:latest'
    build: ./mysql
    env_file:
      - ../env/.env.mysql
